services:
  postgres:
    image: postgres:16.6
    container_name: cloud_postgres
    environment:
      POSTGRES_DB: ${NUMBERS_DB_NAME}
      POSTGRES_USER: ${NUMBERS_DB_USER}
      POSTGRES_PASSWORD: ${NUMBERS_DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${NUMBERS_DB_USER} -d ${NUMBERS_DB_NAME}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - spring-cloud-network

  app:
    container_name: cloud_app
    build:
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_DB: ${NUMBERS_DB_NAME}
      POSTGRES_USER: ${NUMBERS_DB_USER}
      POSTGRES_PASSWORD: ${NUMBERS_DB_PASSWORD}
      MAX_SERVICE_NUMBER: ${MAX_SERVICE_NUMBER}
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge